name: Deploy to Digital Ocean

on:
  push:
    branches:
      - master  # Cambia esto a tu rama de producción

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: |
        cd themes/janejenning
        npm ci
    
    - name: Build
      run: |
        cd themes/janejenning  
        npm run prod
    
    - name: Deploy to Digital Ocean
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DIGITALOCEAN_HOST }}
        username: ${{ secrets.DIGITALOCEAN_USERNAME }}
        key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
        script: |
          cd /var/www/html/wp-content/ 
          git pull origin master
